medusa/backup.py, medusa/cassandra_utils.py, medusa/download.py, medusa/storage/abstract_storage.py, medusa/storage/concurrent.py, medusa/storage/google_cloud_storage/gsutil.py, medusa/storage/google_storage.py, medusa/storage/s3_storage.py, tests/cassandra_utils_test.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py, tests/storage/google_storage_test.py
Two main things needed to happen for SIs to work:
* When discovering files in table folder, Medusa now recursively globs and returns files only.
* When uploading/downloading backups, the SI folder needs to be inserted into the path, otherwise SSTables might clash.
I successfully ran ITs with all 3 storage providers (local, gcp, s3).
=> Support backups of SIs

medusa/cassandra_utils.py
Nodetool might fail - this logs the output.
=> Properly logging nodetool output

medusa/restore_cluster.py
Addresses error in https://github.com/thelastpickle/cassandra-medusa/issues/46
Running this on a real restore the command can be seen populating the temp-dir arg:
```
[ec2-user@ip-172-17-40-6 ~]$ medusa restore-cluster --seed-target 172.17.41.10 --backup-name=test002 --temp-dir /mnt/cassandra/data01/__MEDUSA_TMP_DIR/
[2020-01-08 11:09:04,179] INFO: Monitoring provider is noop
[2020-01-08 11:09:04,179] INFO: system_auth keyspace will be overwritten with the backup on target nodes
[2020-01-08 11:09:05,006] INFO: Ensuring the backup is found and is complete
[2020-01-08 11:09:05,032] INFO: Restore will happen "In-Place", no new hardware is involved
[2020-01-08 11:09:05,056] INFO: Starting Restore on all the nodes in this list: None
[2020-01-08 11:09:05,057] INFO: Starting cluster restore... …
```
=> Pass temp_dir to restore-node command from restore-cluster command

medusa/storage/aws_s3_storage/awscli.py, medusa/storage/aws_s3_storage/concurrent.py, medusa/storage/s3_storage.py
Fixes #52
When using S3, files above the configured threshold (100MB by default) will be downloaded using awscli instead of libcloud.
=> Use awscli for large files downloads

run_integration_tests.sh, tests/integration/features/integration_tests.feature
The tags allow a cleaner way of running integration tests with different storage backends.
=> Use tags to select the storage backend to use

medusa/restore_node.py
I don't know what happened but I had some difficulties to squash the commits (i think that github was with some problems). I'm sorry for the duplicated PR: https://github.com/thelastpickle/cassandra-medusa/pull/82
In ScyllaDB the sstableloader binary doesn't have the ```storage-port``` flag therefore the restore-cluster or restore-node commands fail:
```
[2020-02-18 16:05:52,497] DEBUG: Restoring table view_virtual_columns-08843b6345dc3be29798a0418295cfaa with sstableloader...
Unrecognized option: --storage-port
File "/usr/local/bin/medusa", line 11, in <module>
load_entry_point('cassandra-medusa==0.6.0.dev0', 'console_scripts', 'medusa')()
File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
return self.main(*args, …
```
=> Remove --storage-port arg if default port is 7000

medusa/config.py, medusa/download.py, medusa/medusacli.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
Fix multiple issues:
- #86 `fqdn` not honored in config file
- #90 `medusa download` command does not work due to missing parameter
- #89 `medusa get_last_complete_cluster_backup` explodes if no complete cluster backup exists
=> fix multiple issues: #86,  #89, #90

medusa/verify.py, tests/integration/features/integration_tests.feature
The libcloud local storage provider uses the file modification time instead of the content to compute hashes. This can make comparisons fail if the transfer to the backup folder changes that modification time, although the files have the same contents.
We need to disable the check while we look for an alternate way of computing hashes with local storage.
=> Disable checksum comparisons for the local storage provider.

medusa-example.ini, medusa/cassandra_utils.py, medusa/config.py, tests/cassandra_utils_test.py
This adds an ini parameter "nodetool_ssl" that can be set to true to pass the "--ssl" parameter to nodetool. This is required for SSL JMX connections (https://docs.datastax.com/en/security/5.1/security/secureNodetoolSSL.html)
Related to #99 but I think it's a different issue (cqlsh vs. nodetool)
=> Add ini option to enable --ssl parameter for nodetool

medusa/cassandra_utils.py, medusa/restore_cluster.py
fixes #126 and #132 
Both remote nodetool and ssh wouldn't allow to check if seed nodes are up in most restore scenarios.
I switched to using `nc` to check if the native and/or rpc port are accessible, using the ports from the `cassandra.yaml` file.
=> Fixes restore infinite loop and fqdn resolving in host mapping files

medusa/cassandra_utils.py, medusa/config.py, medusa/restore_node.py, medusa/verify_restore.py, tests/cassandra_utils_test.py, tests/integration/features/steps/integration_steps.py, tests/purge_test.py, tests/restore_cluster_test.py, tests/restore_node_test.py, tests/storage_test.py, tests/storage_test_with_prefix.py
This ended up being bigger than I intended because it turned out the we were still accessing health checks via old `config.restore` sections. We renamed that to `config.checks` some time ago.
As for #72, we've seen plenty of C* processes not going away even after drain and service stop. In these cases we need to do a `kill`. I did not do that in this PR, but if you think we should, I can easily add it.
=> Add wait for node shutdown. Fix healtcheck config. Fixes #72

medusa/restore_node.py
Fixes #136.
Tested and working specifying a keyspace or a table.
=> Keep system keyspaces when user specifies ks/tables

docs/aws_s3_setup.md
ListBucketByTags not available anymore under s3 policy.
=> Remove ListBucketByTags from S3 policy

medusa/backup.py, medusa/cassandra_utils.py, medusa/config.py, medusa/network/__init__.py, medusa/network/hostname_resolver.py, medusa/restore_cluster.py, medusa/restore_node.py, tests/cassandra_utils_test.py, tests/integration/features/steps/integration_steps.py, tests/network/hostname_resolver_test.py, tests/restore_cluster_test.py
Fixes #162 
Also fix config parsing that failed due to "restore" not being changed to "checks" in a previous PR.
I still need to add automatic detection of domain mismatches to either switch automatically to cleaning up the domain or stop and issue an error message asking ops to do it.
=> Add a setting to cleanup fqdn from their domain names and have a consistent view of the hosts

medusa/config.py, medusa/medusacli.py, medusa/restore_cluster.py
Also, the new token enforcement method now allows us to start Cassandra using  `sudo service cassandra start` by default.
=> Restore node should be done in place by default

CHANGELOG.md, medusa/purge.py
Fixes #194 (or part of it - to be determined there)
set() instead of list() with the hope that when a backup is to be deleted because of both age and count, we still only reference the backup one time and delete it once.
=> Avoid double purge (through count + age) of the same backup

CHANGELOG.md, requirements.txt, setup.py
Fixes #208 #201 
Adding dependency to avoid weirdnesses of ssh2-python==0.20.0 that produces bugs at setup & runtime
=> Pin ssh2-python version to 0.19.0

medusa/cassandra_utils.py, tests/cassandra_utils_test.py, tests/resources/yaml/work/cassandra_with_custom_seedprovider.yaml
It turned out Medusa was crashing when doing a backup if custom (non SimpleSeedProvider) was in place.
```
[2020-10-20 13:27:18,837] ERROR: This error happened during the backup: 'seeds'
File "/usr/share/medusa/lib/python3.6/site-packages/medusa/backup.py", line 163, in main
cassandra = Cassandra(config.cassandra)
File "/usr/share/medusa/lib/python3.6/site-packages/medusa/cassandra_utils.py", line 320, in __init__
self.seeds = config_reader.seeds
File "/usr/share/medusa/lib/python3.6/site-packages/medusa/cassandra_utils.py", line 291, in seeds
return self._config.get('seed_provider')[0]['parameters'][0]['seeds'].replace(' ', '').split(',')
KeyError: 'seeds'
```
The seed parsing was introduced in …
=> Tolerate custom seed providers in C* yaml

.dockerignore, .github/workflows/ci.yml, .gitignore, debian/control, debian/rules, packaging/build-deb.sh, packaging/docker-build/Dockerfile, packaging/docker-build/docker-compose.yml, packaging/docker-build/docker-entrypoint.sh
The current debian package generated was not working properly on ubuntu xenial (see #201). This change allows to fix this by extending the way how the debian package is built.
`build-deb.sh` will now build a package for ubuntu 16.04 (xenial) and 18.04 (bionic) 
Both packages version reflect the distribution codename they've been built for, so they can be deployed to the same debian repository.
It would be relatively easy to extend the package build to other ubuntu or debian releases (provided they run a relatively recent python3 and have `dh_virtualenv >= 1.0`).
=> (#201) Ubuntu 16.04 & 18.04 debian packaging

requirements.txt
Offline install was broken (at least on centos 7.8).
setup-tools won't install due to wheel requirements = none
-------------------
Example of install scripts for centos7.8:
yum install python3-pip python3-devel
pip3 install pipenv
wget https://github.com/thelastpickle/cassandra-medusa/archive/v0.7.1.tar.gz
tar zxvf v0.7.1.tar.gz
cd cassandra-medusa-0.7.1
pipenv --python 3
mkdir medusa_dependencies
pip3 download -r requirements.txt -d medusa_dependencies
pipenv run pip3 install -r requirements.txt --no-index --find-links medusa_dependencies/
sudo mkdir /opt/cassandra-medusa
sudo chmod go+rwX  /opt/cassandra-medusa
pipenv run python3 setup.py install --prefix=.  --root=/opt/cassandra-medusa
=> Add wheel package to requirements.txt for offline install

medusa/config.py, tests/cassandra_utils_test.py
Configuration parameter **cassandra.resolve_ip_addresses** is used differently in **medusa/config.py**
```python
if config['storage']['fqdn'] == socket.getfqdn() \
and not evaluate_boolean(config['cassandra']['resolve_ip_addresses']):
config['storage']['fqdn'] = socket.gethostbyname(socket.getfqdn())
```
and in **medusa/cassandra_utils.py** where **CqlSession** constructor is just passing string value of **resolve_ip_addresses** to **HostnameResolver**.
if **medusa.ini** contains **cassandra.resolve_ip_addresses=0** logic **str(self.resolve_addresses) == "False"** in **HostnameResolver** works not as expected and it tries to resolve ip addresses anyway.
Incomplete backup for cluster containing 6 nodes looks like
```
20200830 [Incomplete!]
- Started: 2020-08-30 05:17:09, Finished: never
- …
```
=> Normalized resolve_ip_addresses value

medusa/restore_node.py
Previous versions of Cassandra were more permissive with using the sstableloader without specifying the cipher suites nor the cassandra.yaml location (which allowed to retrieve the cipher suites).
=> Fix failing 4.0 with encryption integration tests

.github/workflows/ci.yml
After #227 and https://issues.apache.org/jira/browse/CASSANDRA-16280 we can remove the experimental flag.*
I removed the exclude / include parts of the matrix (CI workflow) and kept the experimental system in case we need it in the future. Not sure if that's the best approach, let me know your thoughts @adejanovski .
=> Remove experimental flag for Cassandra trunk (4.0)

medusa/backup_cluster.py, medusa/backup_node.py, medusa/cassandra_utils.py, medusa/medusacli.py, medusa/orchestration.py, medusa/restore_cluster.py, medusa/storage/__init__.py, requirements.txt, setup.py, tests/integration/features/steps/integration_steps.py, tests/storage_test_with_prefix.py
Work done:
* New orchestration backups (send to all nodes) --> backup-cluster
* Change pssh_pool_size a mix of: parallel_snapshots, parallel_uploads (for backups) and parallel_restores. Not just create as many ssh commands but make them sync / blocking to enforce the parallelism to be respected
* Build 'backup-node' command as an alias of 'backup' command (add dependency to click_aliases)
* Change snapshots prefixes from '<random UUID>' to 'medusa-'
* Unify pssh_run for cluster backups and restores, created 'orchestration' module.
**Impacts**
* PSSH Pool sizes are now:
- Blocking - previously with a pool of 10 and 500 nodes, within seconds all commands were run as pssh is not waiting for commands to finish to release one connection from the pool
- As a consequence of the above, pools (now …
=> add backup-cluster command + decouple snapshots from upload

medusa/download.py, medusa/filtering.py, medusa/medusacli.py, medusa/restore_node.py, tests/filtering_test.py, tests/integration/features/steps/integration_steps.py, tests/restore_node_test.py
The `medusa download` command allows only to download a whole backup.
This change adds the same filtering flags as the `restore-node` command:
--keyspace <ks>
--table <ks.ta>
This allows to specify which tables or keyspaces combinations medusa will download from the storage.
By default, `medusa download` always downloads the system keyspaces. I added a new option,
`--ignore-system-keyspaces` that allows to not download them. This is very useful if you just want to download a specific keyspace or table.
I noticed that `medusa download` always creates unnecessary local directories (one per keyspace). When downloading only some keyspaces or specific tables, there's no reason all the other keyspaces directory needs to be created. I modified this behavior to only create the downloaded …
=> Allow to download only a set of keyspaces/tables

medusa/restore_node.py
In C* 4.0, we now have peers_v2 (and peer_events_v2). Medusa was not filtering these _v2 tables.
One of the consequent issues was that after a restore, the peers_v2 made it into the cluster and the
CQL driver returned a weird mixture of nodes.
=> Ignore all peer tables, even the v2 ones

.github/workflows/ci.yml, requirements.txt, setup.py
Fixes #248 
Also pin Libcloud dependency to specific versions (>=2.8.0 and <= 3.3.0)
=> Add missing dependencies for Libcloud 3.3.0

medusa/service/grpc/server.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
In case of Exception, Backup and DeleteBackup methods in the gRPC should return an error code. Fixes https://github.com/k8ssandra/k8ssandra/issues/256
=> Backup and DeleteBackup do not return error code

.github/workflows/ci.yml, medusa/cassandra_utils.py, packaging/build-deb.sh, packaging/docker-build/Dockerfile, packaging/docker-build/docker-compose.yml, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
Allow usercert and userkey to be optional
remove Xenial and Stretch from build - deprecate python 3.5
Builds on top of #260 and replaces #177
Fixes #176
=> Update TLS version

docs/azure_blobs_setup.md, medusa/backup_node.py, medusa/storage/azure_blobs_storage/azcli.py, medusa/storage/azure_storage.py, medusa/storage/s3_storage.py
(same PR as https://github.com/thelastpickle/cassandra-medusa/pull/267 - I made this one to clean the git history, as I had merged master a few times). 
2 fixes:
Fix differential backups - I was getting an error that hash_in_manifest was None on this line when trying to run a differential backup with large files.
The fix is similar to #27, when differential backups were broken in s3. I simply copied the multipart file code currently used by s3 to fix the issue.
Our storage accounts are in Azure Gov so I added support to specify a host in the libcloud AzureBlobsStorageDriver connection, as well as a connection_string (which contains host information) in the AWS-cli connection. Unfortunately libclould has a bug in this scenario, so I used a workaround that I found and linked the issue I …
=> Azure Blobs fixes - fix differential backups & specify host parameter

requirements.txt, setup.py
Paramiko, which is pulled as a dep by pssh uses the cryptography dependency with just a lower bound (needs to be >= 2.5).
v3.4.6 of cryptography apparently have a requirement on setuptools_rust which fails the installs in several cases.
=> Pin cryptography to 3.3.2 to avoid install failing on missing Rust req

medusa/storage/__init__.py, medusa/storage/s3_compat_storage/awscli.py, medusa/storage/s3_storage.py, requirements.txt, setup.py, tests/integration/features/steps/integration_steps.py, tests/storage/s3_storage_test.py
Fixes #291
The refactoring of S3 compatible backends included a change on how regions are dealt with, including backwards compatibility for legacy S3 region specific storage providers such as s3_us_west_oregon. The problem with this implementation was that it tried to modify the config object although it's immutable.
=> Fix region replacement in the S3 storage backend

k8s/README.md, medusa/cassandra_utils.py, medusa/config.py, medusa/nodetool.py, medusa/service/snapshot/__init__.py, medusa/service/snapshot/abstract_snapshot_service.py, medusa/service/snapshot/ccm_snapshot_service.py, medusa/service/snapshot/jolokia_snapshot_service.py, medusa/service/snapshot/management_api_snapshot_service.py, medusa/service/snapshot/nodetool_snapshot_service.py, tests/cassandra_utils_test.py, tests/integration/features/environment.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
This PR adds the ability to use the Cassandra [Management API]() in a Kubernetes environment for performing backup and restore functionality, instead of using JMX and needing to have a Jolokia agent embedded into your Cassandra image. This capability is intended for a K8s setup, and requires specific configuration in Medusa to enable.
Included in this PR is a slight refactoring of the `create snapshot` and `delete snapshot` functions, as well as introducing a _snapshot service_ abstraction layer to allow for multiple implementations to manage snapshots in Cassandra.
This should address #262
=> Add ability to use C* Management API for snapshot management

medusa/restore_node.py
And also disable bootstrap (call the same command as start would usually do, but do not start the node).
Related: #303
=> If running in Kubernetes, replace tokens in not in_place case

medusa/purge.py, medusa/storage/abstract_storage.py, medusa/storage/s3_compat_storage/concurrent.py
This is an attempt to fix some issues with S3 during the purge process, where sometimes S3 throws these errors:
```
stderr: [2021-02-25 08:42:21,807] INFO: Monitoring provider is noop
[2021-02-25 08:42:21,807] INFO: Starting purge
[2021-02-25 08:42:22,760] INFO: Listing backups for ip-10-22-22-22.ec2.internal
[2021-02-25 08:42:26,653] INFO: 7 backups are candidate to be purged
[2021-02-25 08:42:26,653] INFO: Purging backup 202102230330 from node ip-10-22-22-22.ec2.internal...
[2021-02-25 08:42:27,099] INFO: Purging backup 202102222130 from node ip-10-22-22-22.ec2.internal...
[2021-02-25 08:42:27,552] INFO: Purging backup 202102230530 from node ip-10-22-22-22.ec2.internal...
[2021-02-25 08:42:27,964] INFO: Purging backup 202102222330 from node ip-10-22-22-22.ec2.internal...
[2021-02-25 …
```
=> Increase retries for S3 storage

medusa/restore_node.py, tests/storage_test.py
Fix the following warnings:
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
```
```
DeprecationWarning: encodestring() is a deprecated alias since 3.1, use encodebytes()
```
=> Fix deprecation warnings

run_integration_tests.sh, tests/storage_test_with_prefix.py
- `./run_integration_tests.sh` can't be run because the shebang is not on the first line
- there is no `generate_md5_hash` symbol in `backup_node`
=> Fix unit tests

k8s/docker-entrypoint.sh, medusa/service/grpc/server.py
This PR includes a couple changes:
* Adds a signal handler for SIGTERM
* When invoked the handler logs that the server is shutting down
* The handler calls `server.stop()` on the gRPC serve
* Use `exec` to run `server.py` so that it is not run in a subshell
=> add handler for sigterm and use exec to run server.py script

medusa/cassandra_utils.py, medusa/restore_node.py, tests/integration/features/steps/integration_steps.py
Replaces #320
Adds the fix for the sstableloader calls from #319
=> Properly cast ports to int type when checking if Cassandra is up

.github/workflows/ci.yml, README.md, docs/Installation.md, docs/Usage.md, docs/ibm_cloud_setup.md, docs/minio_setup.md, tests/integration/features/steps/integration_steps.py
Bintray closing down on May 1st, we're moving the debian packages hosting to cloudsmith.io.
In this PR I've updated the documentations for:
- Installation instructions using the cloudsmith repo
- Fixing inaccuracies in setting up the IBM object storage backend
- Adding information on how to setup MinIO and other S3 compatible backends
There's also a fix for the IBM object storage integration tests.
=> Move from Bintray to Cloudsmith

.github/workflows/ci.yml, debian/rules, medusa/restore_node.py, requirements.txt, setup.py, tests/storage_test.py, tox.ini
Updated parallel-ssh to 1.13.0 as parallel-ssh==1.9.1 failed to build under python 3.9 with following error:
```bash
pssh/native/_ssh2.c:2906:68: error: ‘PyTypeObject {aka struct _typeobject}’ has no member named ‘tp_print’; did you mean ‘tp_dict’?
__pyx_type_4pssh_6native_5_ssh2___pyx_scope_struct___read_output.tp_print = 0;
^~~~~~~~
tp_dic
```
=> * Updated to support python 3.9

medusa/storage/s3_compat_storage/awscli.py, tests/integration/features/steps/integration_steps.py
Fixes #335
When using the default region settings with the `s3_compatible`  storage backend, Medusa would try to get the region from libcloud in order to provide backwards compatibility with the old region specific libcloud S3 storage providers. This would obviously fail as `s3_compatible` is not a valid libcloud storage provider.
This PR fixes this by excluding the `s3_compatible` storage provider from the region resolving path and makes it so that Minio integration tests prevent regressions.
=> Fix S3 compatible backend uploads when no region is specified

medusa/config.py, tests/config_test.py
- Code was missing `[cassandra]` settings override => Make configuration file override more generic
- :warning: Collision found during testing:
- settings are not namespaced in `args` dictionary, so `'enabled'` [is valid](https://github.com/thelastpickle/cassandra-medusa/pull/333/files#diff-698607b1b71bd82ba3f9bc12a10e05bba41fe2bfbfc35d5f6f79bdb69c9353e7R55) for both `[grpc]` and `[kubernetes]` section settings.
- this PR does not aim to fix such collisions
=> Ensure each setting can be overridden

medusa/storage/s3_compat_storage/awscli.py
I've experienced recently upload issues using s3 as storage backend. This is the traceback:
```
File "/usr/local/lib/python3.7/site-packages/medusa/backup_node.py", line 211, in main
cassandra, node_backup, storage, differential_mode, enable_md5, config, backup_name)
File "/usr/local/lib/python3.7/site-packages/medusa/backup_node.py", line 261, in do_backup
num_files = backup_snapshots(storage, manifest, node_backup, node_backup_cache, snapshot)
File "/usr/local/lib/python3.7/site-packages/medusa/backup_node.py", line 347, in backup_snapshots
raise e
File "/usr/local/lib/python3.7/site-packages/medusa/backup_node.py", line 335, in backup_snapshots
manifest_objects += storage.storage_driver.upload_blobs(src_batch, dst_path)
File …
```
=> Add exponential waits in retries for awscli

medusa/network/hostname_resolver.py
During a restore-cluster, when `resolve_ip_addresses` is set to `False`, an empty string is passed to the hostname_resolver which returns this empty string instead of the IP address.
This causes the restore to fail, since sstableloader has then no argument to pass 
```
/opt/cassandra/default/bin/sstableloader', '-d', '',
```
Also I make some parameters mandatory to make sure that medusa behaves as configured (all calls in the codebase do have  those options so it should not break the current behaviors)
=> fix hostname_resolver.resolve_fqdn when resolve_ip_addresses is False

medusa/config.py, medusa/restore_cluster.py, tests/cassandra_utils_test.py, tests/filtering_test.py, tests/integration/features/steps/integration_steps.py, tests/purge_test.py, tests/restore_cluster_test.py, tests/restore_node_test.py, tests/storage_test.py, tests/storage_test_with_prefix.py
Close #352
To persist a custom (i.e. non default) configuration file path, a new attribute is added to `MedusaConfig`. It's not a section like the others but it allows to be self contained.
A `file_path` set to `None` means default configuration file path so we can skip the whole `--config-file ...` part when building restore command.
Unit tests added to test both default and custom configuration file path in command line.
Existing tests migrated to pytest.
=> Use custom config file when restoring data

codecov.yml
This PR will ensure that codecov won't try to evaluate coverage until all parallel CI runs are done, which would yield premature failures in the checks.
Also, since external PRs can't run the cloud integration tests, their coverage is reduced to ~64%. This change will allow the codecov check so succeed at 63% of coverage.
=> add codecov config

medusa/backup_cluster.py, medusa/backup_node.py, medusa/medusacli.py
This makes the `backup-name` optional in the `backup-cluster` command.
I have followed what is done for the `backup-node` concerning the naming scheme
=> backup-cluster default name with timestamp

medusa-example.ini, medusa/config.py, medusa/purge.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py, tests/purge_test.py, tests/resources/config/medusa-azure_blobs.ini, tests/resources/config/medusa-google_storage.ini, tests/resources/config/medusa-ibm_storage.ini, tests/resources/config/medusa-local.ini, tests/resources/config/medusa-local_backup_gc_grace.ini, tests/resources/config/medusa-minio.ini, tests/resources/config/medusa-s3_us_west_oregon.ini, tests/resources/config/medusa.ini
Fixes #363
Protects backup files from being deleted before a configurable gc grace value.
This change prevents purge from deleting sstables of ongoing backups (which are seen as orphaned files).
This PR also reworks the integration tests to use proper config files, which simplifies the integration steps code and expands test coverage to `config.py`.
=> Fix purge race condition

CONTRIBUTING.md, medusa/backup_cluster.py, medusa/backup_node.py, medusa/config.py, medusa/orchestration.py, medusa/restore_cluster.py, medusa/restore_node.py, tests/config_test.py, tests/integration/features/steps/integration_steps.py, tests/orchestration_test.py, tests/resources/config/cassandra.yaml, tests/resources/config/medusa-kubernetes.ini, tests/restore_cluster_test.py
close #318
Introducing a new setting:
```
[cassandra]
use_sudo = False
```
It allows to generate command lines with or without `sudo` prefix. 
When using Kubernetes mode `use_sudo` is forced to `False`.
Seize the opportunity to:
- Add orchestation tests
- Add a medusa.ini for Kubernetes
- Add a `cassandra.yaml` file in test resources to avoid error `RuntimeError: /etc/cassandra/cassandra.yaml is not a file` in tests triggering `Cassandra` class instantation.
- Add doc: declare `pytest` as the only unit test framework to use
=> Make sudo switchable when Kubernetes mode is disabled

docs/Configuration.md, docs/aws_s3_setup.md, medusa-example.ini
Following https://github.com/thelastpickle/cassandra-medusa/pull/373#issuecomment-867385793,  `The s3 storage provider used in conjunction with a region setting is the new way of using libcloud to interact with S3` 
It would probably be good to change the doc, wdyt?
=> update s3 storage_provider documentation

requirements.txt, setup.py
Looks like using Click package versions under 8.x causes this error invoking medusa cli:
```
$ medusa --help
File "/usr/local/bin/medusa", line 5, in <module>
from medusa.medusacli import cli
File "/usr/local/lib/python3.6/dist-packages/medusa/medusacli.py", line 107, in <module>
@click.pass_context
File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 304, in decorator
return option(*(param_decls or ("--version",)), **attrs)(f)
File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 192, in decorator
_param_memo(f, OptionClass(param_decls, **option_attrs))
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1714, in __init__
Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() …
```
=> Fix required version for Click package

docs/Configuration.md, medusa/config.py, medusa/restore_cluster.py, medusa/restore_node.py
I have set up my cassandra clusters such that there is no need for the `medusa` user to run as root. As such, i set `cassandra.use_sudo` to `False`.
However, when doing a cluster restore, execution abruptly failed. On each node, the failure was just after the snapshot data had been pulled down from S3 and was copied into place.
The crux of the stack trace was this:
```
subprocess.CalledProcessError: Command '['chown', '-R', 'cassandra:medusa', '/cassandra/data/myKeyspaceNameHere/myTableNameHere']' returned non-zero exit status 1.
```
Which comes from the non-sstableloader path [here](https://github.com/thelastpickle/cassandra-medusa/blob/5cb39834e7f8ad1c48641af1f1548898bacd5b51/medusa/restore_node.py#L334).
For reasons that are not relevant here, using the `cassandra.use_sudo = True` …
=> [WIP] use `sudo` only during during node-restore operations.

medusa/restore_cluster.py
While trying to use medusa to restore a snapshot to a cluster, I hit a few issues that broke the cluster. Since the cluster was no longer up, i could not use the `--seed-target` argument. I didn't find the `--host-list` argument documented anywhere so I started taking notes as I looked through the code to figure out what the file was supposed to contain and how it was supposed to be used.
I added rudimentary support for comments in the `host-list` file, too.
I can move the documentation from the function def to somewhere in the docs repo if needed.
=> [WIP] add support for comments in the hostmap file

medusa/cassandra_utils.py
While rolling out Medusa @ my org, I ran into an unhandled exception: `ConnectionRefusedError`
Depending on security-group/firewall/OS configuration, a connection to a closed port may either silently fail (looks like a timeout from the connectors' point of view) or an immediate "no!" in the form of a `RST` packet.
In my case, the host that `medusa` was connecting to was up, but the cassandra process was not and hosts in this network are configured to not waste time with stealthy drops.
=> [WIP] explicitly catch ConnectionRefusedError when determining if a host is up/down

.github/workflows/ci.yml, k8s/Dockerfile-azure, k8s/Dockerfile-gcs, k8s/Dockerfile-s3
Fixes https://k8ssandra.atlassian.net/browse/K8SSAND-853
Use a matrix to generate provider specific Docker images with a smaller size, while still generating an uber docker image with the dependencies from all providers.
=> Publish storage provider specific Docker images

medusa/storage/s3_storage.py
To make medusa authenticate to AWS, I've initially been using environment variables to set the access key, secret key and session/security token ([this part of the code](https://github.com/thelastpickle/cassandra-medusa/blob/18562beaa4d2f4affa6ff143a923b69f748accde/medusa/storage/s3_storage.py#L68-L76)). This worked well when using `medusa` commands, as I would just have to generate the credentials before calling the command, using `aws sts` as [described here](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/), because libcloud doesn't automatically assume AMI roles.
I then wanted to use gRPC to issue operations, to be able to use some kind of API and not rely on commands output (especially to list and verify backups). The problem is that I …
=> Use the aws_session_token setting of the aws profile

medusa/backup_node.py, tests/integration/features/integration_tests.feature
This PR fixes an issues that was reported [here](https://forum.k8ssandra.io/t/medusa-restore-systematically-corruption-of-a-table/328/3).
Secondary indexes are stored as subdirectories of the base table directory. When looking for previously backed up files with differential backups, the file name was the only thing used (per keyspace/table) which leads to some confusion between base table files and 2i files if they have the same name and size.
This leads to corrupt backups with manifests that are missing some files, which are then not restored.
This PR retains the subdirectory for cache comparison for secondary index files, avoiding the confusion between files from the base tables and their 2i.
=> Fix corrupt backups when tables have 2i

medusa/cassandra_utils.py
Every time a new cassandra is created Medusa prints a WARNING regarding the value of the is_ccm config.
`[2021-10-29 22:00:03,244] WARNING: is ccm : 0`
This appears to have always been the case the blame on this line points to the initial commit from when the code was imported from Spotify...
I can't really see the purpose for this warning so I recommend it be removed.  If it's useful to know the value of ccm this can probably be an INFO.
=> Remove unnecessary warning regarding is_ccm

medusa-example.ini
I managed to completely miss the `resolve_ip_addresses = True` option as this is mentioned in the docs but wasn't present in the example ini file.
This PR updates the example ini file with options that are mentioned in the docs but were not present in the `medusa-example.ini` file. https://github.com/thelastpickle/cassandra-medusa/blob/master/docs/Configuration.md
=> Update example.ini from docs

medusa/purge.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
Fixes #392.
As described in #392, medusa crashes after deleting backups, during the cleanup phase, when incomplete backups are present.
Skipping backups that have no manifest solves the problem and shouldn't affect in progress backups if `backup_grace_period_in_days` is correctly set.
I can also add logging for incomplete backups if you find it useful.
I ran the new integration test without the fix, and it failed.
With the fix, both integration tests and unit tests are passing.
=> 392: Fix backup deletion with incomplete backups

README.md
Simple documentation adjustment to better inform everyone where to find Docker images.
=> Proposal to add the Docker hub URI to the README

medusa/cassandra_utils.py
If you are using TLS and only listening for CQL TLS connections on port
9142 then medusa will fail to connect because the CqlSessionProvider
only returned a new_session using the default port (9042).
=> Use cassandra native_port for cluster connection

debian/rules
- We need a more recent version of setuptools and pip for python 3.9
- Use pybuild buildsystem to prepare the future: https://wiki.debian.org/Python/Pybuild
=> Fix debian package build with python 3.9

medusa/config.py, medusa/monitoring/__init__.py, medusa/monitoring/dogstatsd.py, requirements.txt, setup.py
This uses the datadog specific statsd package but since only the gauge
metric is used really any statsd package could be used.
The backup-name tag is not sent to datadog to reduce custom metric cost
but can be enabled via the send_backup_name_tag configuration boolean
=> Add a datadog statsd monitoring backend

medusa/storage/concurrent.py, medusa/storage/s3_compat_storage/concurrent.py
This should fix the issues for long running backups using temporary credentials (like AWS IAM role). Right now the problem is those connections are never recycled, and if a backup is running longer than the credentials expiration time, it'll just fail.
This PR set a max TTL for those connections of 20 minutes (it's just an arbitrary number, but should be good enough) and after this period of time, it just resets the connection pool forcing to create new fresh connections.
=> Set TTL for storage connections

medusa/config.py, medusa/storage/s3_base_storage.py, medusa/storage/s3_compat_storage/awscli.py, medusa/storage/s3_storage.py, requirements.txt, setup.py
This leverages `botocore`'s credentials chain, and allows to support all AWS authentication methods without having to re-implement them: [boto/botocore@`master`/botocore/credentials.py](https://github.com/boto/botocore/blob/master/botocore/credentials.py)
This change aims to be fully backward compatible. In addition to everything working before, WebIdentity used for [EKS IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), ECS container profile, `credential_process` and more will be available.
`api_profile` now defaults to an empty string, so no `default` profile is required to be configured.
`region`'s default remains `default`, but when it is `default`, Medusa will let `botocore` figure out the region, it could come from …
=> feat(storage/s3): Use botocore credentials chain

docs/Configuration.md
Add documentation for the option `nodetool_ssl` as used here:
https://github.com/thelastpickle/cassandra-medusa/blob/a00a45593c44b3e4f99adaa1a89475af987c1a9b/medusa/nodetool.py#L21
Note that it may be worth it to change it to a proper boolean instead.
=> Add missing documentation for configuration options

medusa/config.py, tests/config_test.py, tests/resources/config/medusa.ini, tox.ini
* Extended functionality for CQLSH credentials to allow nodetool credentials and keystore/truststore passwords to be defined in environment variables
* Updated environment variables to be prefixed with `MEDUSA_`
* Added deprecated warning message to `CQL_*` environment variables
* Minor change to tox configuration to allow individual unit tests to be executed
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1375) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1375
=> ISSUE-457: Remove plaintext passwords in config

medusa/purge.py
I use k8s pod names as fqdn, so when deleting the backup of `cluster-1`, medusa also deletes the backup of `cluster-10`, `cluster-11`...
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1382) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1382
=> Fix medusa delete-backup fqdn

docs/Installation.md, requirements-gcs.txt, setup.py
I have looked around and I cannot find where this package is used. `libcloud` appears to do everything. It is not even installed by the CI or [Dockerfile-gcs](https://github.com/thelastpickle/cassandra-medusa/blob/master/k8s/Dockerfile-gcs). Please do not hesitate to let me know if I am missing something
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1377) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1377
=> chore: remove GCS dependency group

.gitignore, medusa/backup_cluster.py, medusa/cassandra_utils.py, medusa/config.py, medusa/network/hostname_resolver.py, medusa/restore_cluster.py, medusa/restore_node.py, medusa/service/snapshot/__init__.py, medusa/verify_restore.py, tests/backup_cluster_test.py, tests/config_test.py, tests/network/hostname_resolver_test.py, tests/resources/config/medusa.ini, tests/restore_cluster_test.py, tox.ini
Fixes #464 
Replaces #465 
The changes here modify the way the `HostnameResolver` works by converting FQDNs to simple hostnames in Kubernetes mode.
This allows to both have shorter names but also generate the same hostnames as with cass-operator versions < 1.10.3.
It's done with a simple `fqdn.split('.')[0]` in case the Kubernetes mode is enabled and there's a dot in the fqdn.
I've tried to use a cleaner approach with `socket.gethostbyaddr()`  which returns both the fqdn and a list of aliases, but the aliases are only filled in when resolving the local pod in k8s. Resolving the IP of other pods would return an empty alias list.
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1440) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1440 …
=> Sanitize fqdns for kubernetes deployments

k8s/Dockerfile, k8s/Dockerfile-azure, k8s/Dockerfile-gcs, k8s/Dockerfile-s3
This PR adds support for using the medusa cli inside the docker containers.
Before:
```
$ docker run -it --rm --entrypoint medusa medusa-test
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "medusa": executable file not found in $PATH: unknown.
```
After:
```
$ docker run -it --rm --entrypoint medusa medusa-test
Usage: medusa [OPTIONS] COMMAND [ARGS]...
Options:
( ... )
```
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1374) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1374
=> Build medusa cli in docker files

.github/workflows/ci.yml, k8s/docker-entrypoint.sh, medusa/network/hostname_resolver.py, medusa/restore_cluster.py, medusa/service/grpc/client.py, medusa/service/grpc/medusa.proto, medusa/service/grpc/medusa_pb2.py, medusa/service/grpc/medusa_pb2_grpc.py, medusa/service/grpc/restore.py, medusa/service/grpc/server.py, medusa/storage/google_storage.py, packaging/docker-build/docker-entrypoint.sh, requirements.txt, setup.py, tests/config_test.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py, tests/network/hostname_resolver_test.py, tests/resources/config/medusa-azure_blobs.ini, tests/resources/config/medusa-google_storage.ini, tests/resources/config/medusa-ibm_storage.ini, tests/resources/config/medusa-kubernetes.ini, tests/resources/config/medusa-local.ini, tests/resources/config/medusa-local_backup_gc_grace.ini, tests/resources/config/medusa-minio.ini, tests/resources/config/medusa-s3_us_west_oregon.ini, tox.ini
This PR changes the way restores are performed in Kubernetes.
They are associated with [this k8ssandra-operator PR](https://github.com/k8ssandra/k8ssandra-operator/pull/454).
Restore orchestration was refactored to allow computing the restore mappings without triggering the restore itself. This restore mapping will be stored under `/var/lib/cassandra/.restore_mapping/<restore key>` when the newly created `PrepareRestore()` gRPC operation is invoked.
Then the medusa-restore container will run `medusa/service/grpc/restore.py` as previously, but it was modified to read the mapping file from the restore preparation phase to find which fqdn it should restore from.
The restore mapping bits were simplified to work both with in place and remote restores (nodes are ordered by smallest token and …
=> Allow remote restore in Kubernetes

docs/Configuration.md, medusa/config.py
Required by https://github.com/k8ssandra/k8ssandra-operator/pull/502
The standalone Medusa pod will not manage to resolve its own ip address the way we do for the Cassandra statefulset, requiring to disable hostname resolving specifically for it.
Since the configMap storing `medusa.ini` is shared by both the statefulset and the medusa pod, providing an override through an env variable is the most convenient way of doing this and matches how we handled other settings such as `cql_username`/`cql_password` for example.
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1550) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1550
=> Allow overriding resolve_ip_addresses with an env variable

packaging/docker-build/Dockerfile
When compiling last version of medusa Deb file I faced the following error:
```
=> ERROR [10/11] RUN pip3 install gevent                                                                                                                                                                                                7.7s
------
> [10/11] RUN pip3 install gevent:
#13 0.800 Collecting gevent
#13 1.340   Downloading https://files.pythonhosted.org/packages/c8/18/631398e45c109987f2d8e57f3adda161cc5ff2bd8738ca830c3a2dd41a85/gevent-21.12.0.tar.gz (6.2MB)
#13 2.862   Installing build dependencies: started
#13 7.493   Installing build dependencies: finished with status 'error'
#13 7.493   Complete output from command /usr/bin/python3 -m pip install --ignore-installed --no-user --prefix …
```
=> Dockerfile not working when compiling Medusa on Debian 11 (Buster)

medusa/restore_node.py
Without it, you get errors when the port is not `9042`.
Below is a simulated invocation as medusa would execute it.
```
cassandra@ip-<hidden>:/$ sstableloader -d <hidden> --conf-path /etc/cassandra/cassandra.yaml --username cassandra --password <hidden> /tmp/medusa-restore-0696823c-ffe0-43cf-bc63-57c427138a7f/system_distributed/view_build_status-5582b59f8e4e35e1b9133acada51eb04 -ks /config/ssl/keystore.jks -kspw <hidden>
WARN  10:44:23,021 Small cdc volume detected at /opt/cassandra/data/cdc_raw; setting cdc_total_space_in_mb to 2184.  You can override this in cassandra.yaml
WARN  10:44:23,205 Only 43.651GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
All host(s) tried for query failed (tried: /<hidden>:0 …
```
=> Invoke sstableloader with the transport port that is specified in the cassandra config

medusa/restore_cluster.py, tests/restore_cluster_test.py
~I am still in the process of testing this, but~ I wanted to get this fix out here to get some input on what is and isn't supported regarding materialized views.
Restoring schemas for MVs causes medusa to use the first/second letter of the name instead of the full name and the creation statement, resulting in this crash:
```
File "/home/cassandra/.local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 69, in orchestrate
restore.execute()
File "/home/cassandra/.local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 150, in execute
self._restore_data()
File "/home/cassandra/.local/lib/python3.6/site-packages/medusa/restore_cluster.py", line 347, in _restore_data
self._restore_schema()
File …
```
=> Fix a crash when restoring materialized views

medusa/service/grpc/restore.py
Fixes #492
This will allow setting a temp dir under `/var/lib/cassandra` in K8ssandra so that we have enough room to download the backups.
Currently, it is hardcoded to `/tmp` which is on ephemeral storage and cannot be overridden.
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1609) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1609
=> Add MEDUSA_TMP_DIR env variable for setting the tmp directory in k8s mode

medusa/storage/__init__.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py, tests/storage_test_with_prefix.py
Fixes #485 
The code was so far using a lazy "in" check to select blobs for a specific fqdn. That resulted in "10.0.0.101" blobs being selected when the required fqdn was "10.0.0.10" for example.
This PR fixes this by being more restrictive and given that files are named with the fqdn in last position, checking for the presence of `_{fqdn}.` instead avoids mixing blobs from fqdns/ip addresses with the same prefix.
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1601) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1601
=> fix purge confusion when nodes have the same name prefix

medusa/config.py, medusa/storage/__init__.py
Fixes a problem reported on Discord where the medusa container wouldn't start due to the Azure dependency check consistently blocking the grpc server startup.
Such checks can be disabled when running in kubernetes as we're confident the image contains all the necessary dependencies.
Fixes #508
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1675) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1675
=> Disable dependency checks when running in Kubernetes

docs/Configuration.md, medusa-example.ini, medusa/config.py, tests/config_test.py
Fixes #493 
Allows medusa CQL and nodetool passwords to be stored following a "k8s-like" convention, with a `username` and a `password` file stored in a single directory.
Example:
* `/etc/medusa/secrets/cql/username` contains "my-cql-username"
* `/etc/medusa/secrets/cql/password` contains "my-cql-password"
* `/etc/medusa/secrets/nodetool/username` contains "my-nodetool-username"
* `/etc/medusa/secrets/nodetool/password` contains "my-nodetool-password"
Then the caller should export:
```
MEDUSA_CQL_K8S_PASSWORD_PATH=/etc/medusa/secrets/cql
MEDUSA_NODETOOL_K8S_PASSWORD_PATH=/etc/medusa/secrets/nodetool
```
And put the corresponding passwords in the 4 files mentioned above. Hopefully this is the k8s standard way of exporting secrets. In this model it is the responsibility of Medusa to be able …
=> [k8s] supporting k8s-style secrets stored in a folder

medusa/cassandra_utils.py, medusa/network/hostname_resolver.py
Fix to work better in ipv6 only environment (k8ssandra cluster) (fixes #560)
This change tries to call socket.getaddrinfo after socket.gethostbyname fails.
socket.gethostbyname always fails in case there is no ipv4 address(but there can be ipv6 address).
socket.gethostbyname is called first to make sure behavior does not change for dual stack cases.
=> improve ipv6 compatibility (fixes #560)

medusa/storage/azure_blobs_storage/concurrent.py
SSTable-Attached Secondary Index (SASI) files (SI_*.db) could be empty. Medusa uses azure storage driver from libcloud to upload small files and az cli command to upload large files. However, libcloud fails to upload empty files with 403 error. Thus, we could use az cli command to upload empty files.
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1825) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1825
=> upload empty files with az cli command

bin/medusa-wrapper, docs/Configuration.md, docs/minio_setup.md
When using medusa with an own-hosted S3 storage available via https an environment variable `SSL_CERT_FILE` needs to be set up. The backup-cluster subcommand, however, would fail, as the environment variables aren't sent via SSH. This patch allows the medusa-wrapper to source an environment file before calling the medusa backup on the local nodes.
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1839) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1839
=> enable sourcing environment file within wrapper

medusa/backup_node.py, medusa/storage/abstract_storage.py, medusa/storage/s3_base_storage.py, medusa/storage/s3_storage.py
Hi,
We have faced duplication parameters in the ".aws/config" file because "set_upload_bandwidth" is being called in parallel by multiple threads.
> cassandra@cass-01: ~$ more .aws/config
> [default]
> s3 =
> max_bandwidth = 250MB/s
> [default]
> s3 =
> max_bandwidth = 250MB/s
I have contacted AWS support team, and they said that "aws configure set default.s3.max_bandwidth 250Mb/s" is not thread-safe and It doesn't support multiple calls of this command at the same time.
This command should be executed once in medusa at start-up. No need to execute it by each thread.
I have fixed this in the medusa source code by renaming "set_upload_bandwidth" to "prepare_upload" and executing it only once in the "handle_backup" method. Similar to the "preapre_download" method.
=> Concurrent calls of set_upload_bandwidth cause duplication in ".aws/config"

medusa/service/grpc/restore.py, medusa/service/grpc/server.py, tests/service/grpc/restore_test.py
Fixes #591 
Reads the restore mapping from an environment variable instead of a file.
The local node is identified by the POD_NAME env variable, which is used to locate the right entry in the restore mapping.
The `source` value is used as `POD_IP` in the mapping in order to restore the right dataset.
This PR also refactors the `restore.py` file to make it testable and add some proper tests for it.
=> Read the restore mapping from an env variable in k8s restore mode

.github/workflows/ci.yml, medusa/storage/__init__.py, medusa/storage/abstract_storage.py, medusa/storage/local_storage.py, tests/storage_test.py, tests/storage_test_with_prefix.py
Fixes #595.
I'm proposing filtering the 0-sized files one step lower than the issue suggests. Doing the filter in list_backups() would need more changes around the codebase, for example in the functions dealing with validating the backup. This way I only had to patch the local and abstract storage list_objects().
=> Skip 0-sized blobs when listing storage. Fixes #595.

.github/workflows/ci.yml
Fixes #609 
This was tested in previous runs that had some comments in CI to build the images on PR pushes.
[This tag](https://hub.docker.com/layers/k8ssandra/medusa/be90ce5b/images/sha256-4464c8ac50048bb34035b53111887c44c3a936a0285ebc53183105d6ab398bf9?context=explore) can be used for testing the image.
=> Use docker buildx for building multi arch images

medusa/config.py, tests/config_test.py
=> added check for bucket name validation

medusa/backup_cluster.py, medusa/backup_node.py, medusa/restore_cluster.py
- When backup duration is >24h, the .seconds conversion only convert the second of the day, not the full duration.
- This fix #606
=> Fix reported time in seconds in metrics when backup are >24h

medusa/storage/abstract_storage.py, medusa/storage/s3_base_storage.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
I'm still not happy that we pass in the headers differently for upload blob from file vs upload blob from a stream.
I'm also not happy with how eloquent the ITs are, but it's probably still better than hardcoding blob paths.
Fixes #612.
=> [Storage] Pass KMS headers when uploading blobs

.gitignore, medusa/medusacli.py, medusa/purge_decommissioned.py, medusa/storage/__init__.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py, tests/purge_decommissioned_test.py
=> purge decommissioned nodes backups

medusa/backup_node.py, medusa/storage/s3_base_storage.py, requirements.txt, setup.py
=> Use Boto3 for S3 communications

.github/workflows/ci.yml, medusa/service/grpc/restore.py, tests/integration/features/integration_tests.feature, tests/service/grpc/restore_test.py
Fixes restore.py (used in the medusa-restore init container of k8ssandra-operator) which fails if a backup cannot be found.
This actually happens when scaling up a cluster after a restore, and is expected so it shouldn't exit with failure but gracefully.
It also invokes relevant e2e tests in k8ssandra-operator so we can make sure the restore.py script still works with it and add non regression checks.
=> Fix k8s restore no backup (v0.15)

medusa/storage/s3_base_storage.py, tests/storage/s3_storage_test.py
=> [S3 Storage] Refactor S3 (or S3-compatible) URL creation

medusa/config.py, medusa/service/grpc/server.py
Sets the default values to 512MB for send and 128MB to recv (I don't see why Medusa would receive larger messages in the gRPC layer).
Fixes #673
=> Add gRPC config values to configure max send and max receive sizes

medusa/service/grpc/client.py, medusa/service/grpc/medusa.proto, medusa/service/grpc/medusa_pb2.py, medusa/service/grpc/medusa_pb2_grpc.py, medusa/service/grpc/server.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py, tests/server_test.py
=> [gRPC] Add GetBackup() endpoint

.github/workflows/ci.yml, .gitignore, medusa/backup_node.py, medusa/cassandra_utils.py, medusa/config.py, medusa/nodetool.py, medusa/restore_node.py, medusa/storage/abstract_storage.py, medusa/storage/azure_storage.py, medusa/storage/google_storage.py, medusa/storage/local_storage.py, medusa/storage/node_backup.py, medusa/storage/s3_base_storage.py, tests/cassandra_utils_test.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py, tests/resources/config/medusa-local-dse.ini, tests/resources/config/medusa-s3_us_west_oregon-dse.ini, tests/resources/dse/configure-dse-search.sh, tests/resources/dse/configure-dse.sh, tests/resources/dse/delete-dse.sh, tests/resources/dse/download-dse.sh, tests/resources/dse/run-command.sh, tests/resources/dse/solr-config.xml, tests/resources/dse/solr-schema.xml, tests/resources/dse/start-dse.sh, tests/resources/dse/stop-dse.sh
=> Support DSE (with Search)

medusa/storage/s3_base_storage.py, tests/storage/s3_storage_test.py
Fix https://github.com/thelastpickle/cassandra-medusa/pull/691
=> feat(iam): support assume role

medusa/cassandra_utils.py, medusa/service/snapshot/nodetool_snapshot_service.py, tests/cassandra_utils_test.py, tests/integration/features/integration_tests.feature
=> Prevent recursive DSE snapshots

k8s/Dockerfile, k8s/medusa.sh, medusa/service/grpc/client.py, medusa/service/grpc/server.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
Fixes https://github.com/k8ssandra/k8ssandra-operator/issues/1183
Fixes https://github.com/k8ssandra/k8ssandra-operator/issues/1231
Fixes https://github.com/thelastpickle/cassandra-medusa/issues/721
The GRPC's AsyncBackup endpoint was not async. It was blocking until the backup finished. This PR fixes that, and then adjusts the ITs so that they work with the new async implementation. 
I've also touched the logging during ITs so that we don't have thousands of lines about Cassandra not being yet available.
I've also touched how we build the Medusa container image for k8s; it now has the Medusa entry point on the system path again.
Aside from the ITs, I've tested this by:
- manually hitting the (Async)Backup endpoints with Bloom RPC
- loading a Medusa image built off this branch into a k8s …
=> Make grpc's AsynBackup trully Async

k8s/Dockerfile
Update GRPC_HEALTH_PROBE_VERSION to version 0.4.25
=> Update GRPC_HEALTH_PROBE_VERSION to version 0.4.25

medusa/backup_manager.py, medusa/service/grpc/server.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py, tests/service/grpc/server_test.py
Fixes #515 .
There was a bug in the `GetBackupStatus` endpoint. If it got hit on a fresh server (such that that particular python process never seen the creation of the requested backup), then it would not be able to report the status of the backup, and complain something along the lines of:
```
File "/.../cassandra-medusa/medusa/backup_manager.py", line 73, in get_backup_status
if backup_name not in BackupMan.__instance.__backups:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_BackupMan__backups'
```
This PR fixes that by (re)registering the backup once we list it during answering the `GetBackupStatus` request.
Edit: The debian build is failing because [this](https://github.com/thelastpickle/cassandra-medusa/pull/716/files#diff-9852e2a81ec69c8ecf9eb81d …
=> Fix GetBackupStatus endpoint on a fresh gRPC server

medusa/backup_node.py, medusa/storage/__init__.py, medusa/storage/abstract_storage.py, medusa/storage/azure_storage.py, medusa/storage/google_storage.py, medusa/storage/local_storage.py, medusa/storage/s3_base_storage.py, medusa/storage/s3_rgw.py, packaging/docker-build/Dockerfile, tests/backup_node_test.py, tests/backup_test.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py, tests/storage_test.py
Fixes #709
Fixes #368 
In short, the way we do this is to list all files in storage, in the data folder for the given prefix and node,  _after_ doing a snapshot but _before_ we start backing up individual tables. We we then group the listed files into a dict->dict->set keyed by keyspace->table, so that we can look up any given file efficiently. 
Tested manually on a node with ~11k LCS SSTables. Did not observe a particular increase in (differential) backup duration.  There probably is an increased memory consumption, but I'm struggling a bit to quantify how much.
=> Re-upload files if they are missing in storage

medusa/cassandra_utils.py
Fixes [#497](https://github.com/thelastpickle/cassandra-medusa/issues/497)
=> Change is_open function's log level messages from error to debug.

k8s/docker-entrypoint.sh, medusa/backup_manager.py, medusa/backup_node.py, medusa/service/grpc/server.py, medusa/utils.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
Fixes https://github.com/k8ssandra/k8ssandra-operator/issues/1256
Fixes https://github.com/k8ssandra/k8ssandra-operator/issues/1255
This PR adds the feature of reloading Medusa's configuration when running within the k8ssandra-operator.
The implementation has two parts:
* Medusa will touch a file in `/tmp` to indicate a backup is running. This is easily detectable from a shell w/o invoking anything special (another Medusa instance included).
* The entry point of the Docker image we use in k8ssandra-operator will start Medusa and then proceed to watch the `medusa.ini` file for changes by recalculating its digest every 5 seconds. If the digest changes, it'll check for running backups. If there are none, it'll kill the Medusa's gRPC process and exit, thus killing the entire container.
The …
=> Make a tempfile while backup is running

medusa/scripts/medusa-wrapper.sh, medusa/scripts/medusa_wrapper.py, pyproject.toml
Fixes https://github.com/thelastpickle/cassandra-medusa/issues/735.
Tested on a blank EC2 Ubuntu 22.04 instance by running:
```
sudo apt-get update
sudo apt-get install -y python3-pip
pip install git+https://github.com/thelastpickle/cassandra-medusa.git@radovan/fix-wrapper
logout
(log back in)
$ medusa-wrapper
$
```
This installs Medusa to `/home/ubuntu/.local/lib/python3.10/site-packages/medusa`. The wrapper script is in there too now, because poetry does not have a way to bundle it in otherwies.
One other thing I spotted is that the `medusa-example.ini` file lands in `/home/ubuntu/.local/lib/python3.10/site-packages/medusa-example.ini`, which is perhaps not the nicest.
=> Add bin/medusa-wrapper to package's installed scripts

medusa-example.ini, medusa/config.py, medusa/storage/azure_storage.py, medusa/storage/google_storage.py, medusa/storage/s3_base_storage.py, tests/storage/azure_storage_test.py
=> Make read timeout configurable

k8s/Dockerfile, k8s/README.md
Adding support for creating images for multiple architectures using docker buildx, this will also fix the issue with the grpc-health-probe binary referenced here:
Fixes #759
=> Adding support to build images for multiple architectures

.github/workflows/ci.yml, medusa/backup_manager.py, medusa/service/grpc/server.py, tests/service/grpc/server_test.py, tests/storage_test.py
Fixes #797 
Two bugs are fixed in this PR:
- The `BackupMan.register_backup()` function was always registering the backup, even if it existed and overwrite was set to false due to bad code structure.
- The state was computed without taking into account the presence of a future. In case of a restart of the grpc server with an unfinished backup job, the backup would forever be seen as in progress even though it failed.
=> Fix backup man future registration and BackupStatus computation of the node backup state

k8s/docker-entrypoint.sh
Resolve https://github.com/thelastpickle/cassandra-medusa/issues/805
Prior to this change, if the Medusa process exits with a non-zero exit code for some reason, the Medusa container will be stuck forever because of the `while true` loop.
With this fix, the while loop will be interrupted if the Medusa process exits, and the container will exit with the same code as the Medusa process exit code.
To validate this change, I've manually tested the following scenarios:
=> Propagate Medusa process exit code in k8s docker-entrypoint

docs/Configuration.md, medusa/config.py, medusa/orchestration.py, tests/orchestration_test.py
This change adds two parameters to the `[ssh]` section in `medusa.ini`:
- `keepalive_seconds` : seconds between ssh keepalive messages to the ssh server. Default to 60 seconds. Due to a limitation in parallel-ssh, if `cert_file` is defined, then `keepalive_seconds` will be ignored and no keep alive messages will be sent
- `use_pty` : Boolean: Allocates a pseudo-terminal. Default to False. It's useful if sudo settings require a tty
`parallel-ssh` includes two implementations of a parallel ssh client:
1.  [Native Parallel Client](https://parallel-ssh.readthedocs.io/en/latest/native_parallel.html) - Based on `ssh2-python` (`libssh2`) .
2.  [ssh-python Parallel Client](https://parallel-ssh.readthedocs.io/en/latest/ssh_parallel.html) - Based on `ssh-python` (`libssh`)
Medusa uses …
=> added ssh keepalive and pseudo terminal support to orchestrator

.github/workflows/ci.yml, medusa-example.ini, medusa/config.py, medusa/storage/azure_storage.py, medusa/storage/google_storage.py, medusa/storage/s3_base_storage.py, run_integration_tests.sh, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py, tests/resources/config/medusa-s3_us_west_oregon.ini, tests/storage/abstract_storage_test.py
=> MED-100 Make read_timeout default to None, only use it if set

docs/Configuration.md, medusa-example.ini, medusa/config.py, medusa/service/grpc/server.py, tests/integration/features/steps/integration_steps.py
This change adds one parameter to the `[grpc]` section in `medusa.ini`:
- `port` : grpc port the server listens to. Defaults to 50051
This change resolves [#512](https://github.com/thelastpickle/cassandra-medusa/issues/512)  (_grpc service - port number configurability_) on the Medusa side. 
Other projects such as k8ssandra-operator will need changes to support the new parameter.
=> Added configuration parameter grpc.port to make the gRPC server port configurable

docs/Configuration.md, docs/gcs_setup.md, medusa/storage/google_storage.py
Support using service accounts that are attached to a GCE instance, rather than requiring a service account key to be present.
The `gcloud-aio` library supports using a service account that is assigned to a VM by default just by omitting the `service_file` parameter (or by setting it to `None`).
Removing this requirement means that the service account key does not need to be manually rotated, as the assigned service account credentials provided by the GCE metadata API are automatically rotated frequently. 
Closes: #833
=> Add support for using an attached GCE service account

docs/Configuration.md, medusa-example.ini, medusa/config.py, medusa/orchestration.py, tests/orchestration_test.py
=> Add flag to enable login shells

k8s/Dockerfile, poetry.lock, pyproject.toml
Brings in fixes to:
* [CVE-2024-12797](https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-8715586) - cryptography bumped from 42.0.4 to 44.0.1 in this PR.
* CVE-2024-45337 - the [latest](https://github.com/grpc-ecosystem/grpc-health-probe/blob/master/go.mod#L5) grpc health probe has `golang.org/x/crypto v0.35.0 `, which has been [released](https://github.com/grpc-ecosystem/grpc-health-probe/releases/tag/v0.4.36), so latest gets it.
* CVE-2024-6345 - setuptools bumped/set in this PR
* CVE-2023-45288 - correct `golang.org/x/net` is used in the most recent health probe
=> MC-1582 Bump versions of some python deps + grpc health probe

docs/azure_blobs_setup.md, docs/gcs_setup.md, medusa/storage/azure_storage.py, medusa/storage/google_storage.py, tests/storage/azure_storage_test.py
Fixes #856.
According to preliminary testing, this kinda works:
```
export AZURE_STORAGE_ACCOUNT=medusaintegrationtests
medusa -v --config-file medusa.ini list-backups
[2025-02-17 11:40:20,383] DEBUG: Loading configuration from medusa.ini
[2025-02-17 11:40:20,391] INFO: Resolving ip address
[2025-02-17 11:40:20,397] INFO: ip address to resolve 10.3.0.4
[2025-02-17 11:40:20,398] DEBUG: Resolved 10.3.0.4 to azure-backup.internal.cloudapp.net
[2025-02-17 11:40:20,399] DEBUG: Loading storage_provider: azure_blobs
[2025-02-17 11:40:20,399] DEBUG: No credentials file specified, using DefaultAzureCredential
[2025-02-17 11:40:20,400] INFO: No environment configuration found.
[2025-02-17 11:40:20,401] INFO: ManagedIdentityCredential will use IMDS
[2025-02-17 11:40:20,404] DEBUG: [Storage] Listing …
```
=> MC-1534 Allow using role-based identity for Azure storage

medusa/medusacli.py
Else:
```
$ medusa purge-decommissioned
[2025-08-14 21:13:55,306] WARNING: Forcing use_sudo to False because Kubernetes mode is enabled
File "/usr/share/cassandra-medusa/bin/medusa", line 8, in <module>
sys.exit(cli())
File "/usr/share/cassandra-medusa/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/usr/share/cassandra-medusa/lib/python3.10/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File "/usr/share/cassandra-medusa/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/share/cassandra-medusa/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, …
```
=> Add medusa.purge_decommissioned import to cli
