.github/workflows/pythonapp.yml, medusa/cassandra_utils.py, medusa/restore_node.py, run_integration_tests.sh, tests/integration/features/steps/integration_steps.py
Remove duplicate call to flake8
=> Cleanup ci workflow

.github/workflows/ci.yml, .github/workflows/publish.yml, medusa/storage/aws_s3_storage/concurrent.py, medusa/storage/concurrent.py, setup.py, tests/cassandra_utils_test.py, tox.ini
=> Fix compatibility with python3.5

README.md, medusa-example.ini, medusa/config.py, medusa/medusacli.py, tests/cassandra_utils_test.py, tests/integration/features/steps/integration_steps.py, tests/purge_test.py, tests/restore_cluster_test.py, tests/restore_node_test.py, tests/storage_test.py
~If `--log-file` is passed, the log will _also_ go into a file.~
- Added logging to file.
- Added logging configuration in `medusa.ini`
=> Basic logging to file

README.md, docs/ceph_s3_setup.md, medusa/backup.py, medusa/config.py, medusa/storage/__init__.py, medusa/storage/s3_rgw.py, medusa/storage/s3_storage.py
Hi, this is a proposal to add S3_RGW to the list of supported providers.
I'm actually not sure how to add tests - or even if I need to so. I have been using in our setup and it's working fine.
Aims to solve #31
=> Support for S3_RGW (CephFS S3-compatible API)

README.md, medusa-example.ini, medusa/cassandra_utils.py, medusa/config.py, tests/cassandra_utils_test.py
=> Set nodetool parameters

medusa/storage/s3_storage.py, requirements.txt, setup.py
Adding support for OS Environment credentials and IAM Role credentials. Any problem/change please feel free to request changes.
=> Adding support for Env Credentials and IAM Role

medusa/restore_cluster.py, medusa/restore_node.py, medusa/storage/s3_storage.py
Fix schema recreation when restoring using the sstableloader
Unthrottle downloads for AWS S3
=> Fix sstableloader calls for clusters without authentication

.github/workflows/ci.yml, medusa/backup.py, medusa/index.py, medusa/storage/__init__.py, medusa/storage/s3_storage.py, run_integration_tests.sh, tests/integration/features/environment.py, tests/integration/features/steps/integration_steps.py, tests/storage_test_with_prefix.py
Enable S3 integration tests in GitHub Actions
Fixes #13
=>  Fix the usage of prefix for multi tenant buckets

medusa/config.py, medusa/restore_cluster.py
Customized port added to SSH when restoring a cluster.
=> Add customized ssh port on restore-cluster

README.md, medusa-example.ini, medusa/restore_node.py
Updated documentation regarding SSH port. PR: https://github.com/thelastpickle/cassandra-medusa/pull/76
=> Add ssh port info to Readme.md and medusa-example.ini

README.md, medusa/config.py, medusa/storage/aws_s3_storage/awscli.py, medusa/storage/s3_storage.py
Dynamically find awscli binary 
This more so  a example for issue  https://github.com/thelastpickle/cassandra-medusa/issues/78
=> Allow awscli use on venvs

medusa/medusacli.py, medusa/purge.py, medusa/restore_cluster.py, medusa/storage/__init__.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
Aims at fixing #18 --> Allow deleting backups
* Tested manually and working.
* Integration tests running manually.
* Needs review.
=> Add a delete-backup command

medusa/storage/concurrent.py
Related to #58.
Changes uploading and downloading to use the stream methods `upload_object_via_stream` and `object.as_stream()`
=> Use streams for uploading and downloading

medusa/backup.py, tests/integration/features/integration_tests.feature
I had the integration tests run against local and AWS storage.
=> Make 1st differential backup upload all files, even if a full one exists. Fixes 108

medusa/cassandra_utils.py, medusa/medusacli.py, medusa/restore_cluster.py, tests/cassandra_utils_test.py, tests/resources/restore_cluster_tokenmap.one_changed.json, tests/resources/yaml/original/cassandra_no_tokens.yaml, tests/resources/yaml/original/cassandra_with_tokens.yaml, tests/resources/yaml/original/cassandra_with_tokens_and_autobootstrap.yaml, tests/resources/yaml/work/cassandra_no_tokens.yaml, tests/resources/yaml/work/cassandra_with_tokens.yaml, tests/resources/yaml/work/cassandra_with_tokens_and_autobootstrap.yaml, tests/restore_cluster_test.py
fixes #142
fixes #133 
fixes #130
=> Enforce tokens by modifying cassandra.yaml instead of setting env vars

medusa/medusacli.py
@adejanovski I had this change left behind (not committed on my last PR, so not merged...)
How does it look for you? Do we want this little change in?
=> specify resotre specific keyspaces/tables usage

medusa/backup.py, medusa/config.py, medusa/restore_node.py, tests/integration/features/environment.py
Fixes #26, #109 an #164.
Fixes master bug in config: https://github.com/thelastpickle/cassandra-medusa/pull/168/files#diff-3feb4fc181a6e98475e3a0899f71011f
Improve tests (so they show the error better): https://github.com/thelastpickle/cassandra-medusa/pull/168/files#diff-dab28e770b45220deae663cad43f2227
=> Do not delete cleanup and saved_caches folders

medusa/backup.py, medusa/download.py, medusa/storage/__init__.py, medusa/storage/google_storage.py
gsutil cp uploading/downloading issue. fix feeding plenty of files to gsutil's stdin which causes fail.
=> Fix gsutil upload/download 

.github/workflows/ci.yml, medusa/restore_node.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
Fix fqdn resolving issues in integration tests and restore-node
=> Add GCS integration tests

medusa/cassandra_utils.py
=> Do not rely on nc command output, use returncode instead

.github/workflows/ci.yml, medusa/restore_node.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
Commits missing in master, recovered from 0.7 branch
=> Alain/commits from 0.7

.github/workflows/ci.yml, CHANGELOG.md, medusa/cassandra_utils.py
Further delay consecutive reconnection attempts
=> Attempt to fix flakey tests

CHANGELOG.md, medusa/cassandra_utils.py
=> Remove nc (netcat) dependency, use python socket instead

docs/gcs_setup.md
Testing GCP setup (new bucket etc) today, I had troubles with instructions, that I amended.
=> Improve/fix instructions for GCS

.gitignore, requirements.txt, setup.py
Fixes #250 
Fixes #233
Replaces #254
=> Replace the pycrypto dependency with pycryptodome

k8s/Dockerfile, requirements-grpc-runtime.txt, requirements.txt
New:
```
REPOSITORY                                 TAG        IMAGE ID       CREATED             SIZE
<none>                                     <none>     e8830ab83fb8   13 minutes ago      372MB
```
Old:
```
<none>                                     <none>     712150e5744f   4 hours ago         2.04GB
```
Will require some real testing to ensure all the features work.
Intended to fix https://github.com/k8ssandra/k8ssandra/issues/191
=> Use multi-stage building in the Dockerfile to reduce image size

k8s/Dockerfile
Also remove unnecessary app directory
=> Fix home/medusa directory with correct rights

medusa/purge.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
=> Include storage prefix during file purge process

.github/workflows/ci.yml, medusa/cassandra_utils.py, tests/integration/features/steps/integration_steps.py
=> Build and publish Docker image during releases

medusa/cassandra_utils.py
=> typo from issue reported by a user

medusa/service/grpc/restore.py
Fixes https://github.com/k8ssandra/k8ssandra/issues/461
=> Bypass the restore in GRPC/k8s mode if the backup doesn't exist

.coveragerc, .github/workflows/ci.yml, .gitignore, README.md, tox.ini
Fixes #345
@jeffbanks, if we merge this PR you'll be able to rebase on top of `master` to get your PR pass CI.
=> Switch to codecov.io for code coverage

docs/Configuration.md, medusa-example.ini, medusa/config.py, medusa/orchestration.py, requirements.txt, setup.py
This adds support for ssh via public certificates
=> support ssh with public certificates

docs/design.md, medusa/cassandra_utils.py, tests/cassandra_utils_test.py, tests/resources/restore_cluster_tokenmap.json
Includes effort to introduce `dc` and `rack` into the CqlSession `tokenmap` accessible from c* utility.
=> Placement awareness - dc and rack

medusa/service/grpc/server.py
This is an attempt at solving
https://github.com/thelastpickle/cassandra-medusa/issues/389
Criticisms and comments gladly recieved...
=> Make use of the backup mode passed in protobuf message

.github/workflows/ci.yml, requirements-azure.txt, setup.py
Following up on @adutra's comment in #400 to make `requirements-azure.txt` consistent with the Docker image deps.
=> Make Azure requirements consitent with the Docker image

k8s/docker-entrypoint.sh
=> Remove use of exec for containerized restore operations

medusa/service/grpc/restore.py
Fixes #443
K8s restore script was mistakenly removed in a previous PR as it was untested.
=> Re introduce k8s restore file

.github/workflows/ci.yml, medusa/cassandra_utils.py, medusa/config.py, medusa/nodetool.py, medusa/service/snapshot/ccm_snapshot_service.py, setup.py, tests/cassandra_utils_test.py, tests/integration/features/integration_tests.feature, tests/resources/config/medusa-azure_blobs.ini, tests/resources/config/medusa-google_storage.ini, tests/resources/config/medusa-ibm_storage.ini, tests/resources/config/medusa-kubernetes.ini, tests/resources/config/medusa-local.ini, tests/resources/config/medusa-local_backup_gc_grace.ini, tests/resources/config/medusa-minio.ini, tests/resources/config/medusa-s3_us_west_oregon.ini, tests/resources/config/medusa.ini
Fixes #472
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1490) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1490
=> Add rmi legacy url parsing to fix jdk upgrade related issues with nodetool

tests/resources/config/medusa-s3_us_west_oregon.ini
Use a new bucket for integration tests
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1506) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1506
=> Change S3 bucket for integration tests

medusa/service/grpc/restore.py
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1512) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1512
=> Fix restore in K8ssandra with GHA runners

.github/workflows/add_to_project.yaml, .github/workflows/check_pr_linked_issue.yaml
Add GHA workflows to add new issues to the k8ssandra project board and check that open PRs have a linked issue.
┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1883) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1883
┆Priority: Medium
┆Link To Issue: https://k8ssandra.atlassian.net/browse/K8SSAND-1883
=> Add GH project automation

.github/workflows/ci.yml
=> Switch GHA runners to Ubuntu 20.04

medusa/verify.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
[#576](https://github.com/thelastpickle/cassandra-medusa/issues/576)
=> Eliminate verify on Statistics.db files to Fix #576

medusa-example.ini
=> Remove misleading comment in example ini file

medusa/backup_cluster.py, tests/backup_cluster_test.py
=> Fix a test for orchestrate backup

medusa/storage/__init__.py, medusa/storage/abstract_storage.py, medusa/storage/azure_storage.py, medusa/storage/google_storage.py, medusa/storage/s3_base_storage.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py, tests/resources/config/medusa-minio.ini
=> [Storage] Paginate listing objects where needed

medusa/service/grpc/server.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
=> [gRPC] Fix how we read the missing nodes in the gRPC server

.github/workflows/ci.yml, medusa/download.py, medusa/storage/abstract_storage.py, medusa/storage/azure_storage.py, medusa/storage/google_storage.py, medusa/storage/local_storage.py, medusa/storage/s3_base_storage.py, tests/download_test.py, tests/integration/features/steps/integration_steps.py
=> Add check for free space before downloading a backup

requirements.txt, setup.py
=> Pin click-aliases dependency

docs/azure_blobs_setup.md, medusa/storage/azure_storage.py, tests/storage/abstract_storage_test.py, tests/storage/azure_storage_test.py, tests/storage/google_storage_test.py, tests/storage/s3_storage_test.py
=> [Azure Storage] Honor host/port from config

medusa/service/grpc/medusa.proto, medusa/service/grpc/medusa_pb2.py, medusa/service/grpc/server.py, tests/purge_test.py, tests/service/grpc/server_test.py, tests/storage_test.py, tox.ini
=> Make gRPC Service's BackupStatus return a node backup

medusa-example.ini, medusa/config.py, medusa/storage/s3_base_storage.py, tests/storage/s3_storage_test.py
=> Allow enabling/disabling SSL certificate verification

medusa/storage/azure_storage.py
=> [Storage] Make Azure Storage use big upload chunks by default

medusa/storage/abstract_storage.py
Fixes https://github.com/thelastpickle/cassandra-medusa/issues/743
=> Add a retry annotation to list_blobs

medusa/backup_cluster.py, medusa/medusacli.py
=> Fix to enable the creation of backups when a backup name is not provided

medusa/storage/__init__.py, tests/storage_test.py
=> Fix a bug where 'None' got into the path prefix we actually list with

medusa/restore_cluster.py, tests/resources/restore_cluster_host_list.txt
=> Ignore blank likes in host_list file

medusa/storage/google_storage.py, tests/storage/abstract_storage_test.py
=> Do not set storage class for GCP (it's not supported anyway)

medusa/verify.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
=> MED-95 Handle updated Summary.db components

medusa-example.ini, medusa/config.py, medusa/storage/s3_base_storage.py
I've taken the change proposed in #790 and rebased it to fix conflicts with master.
Fixes #790
=> Support s3 address style config

medusa/backup_cluster.py, medusa/backup_node.py, medusa/cassandra_utils.py, medusa/medusacli.py, tests/backup_cluster_test.py, tests/integration/features/integration_tests.feature, tests/integration/features/steps/integration_steps.py
Fixes #851
Fixes #852 
This PR adds a few minor finishing touches to #852.
=> 851 Backup Without Snapshot Creation & Deletion - Finishing Touches
